/* GENERATED by scripts/optimize-images.mjs — do not edit by hand. */

export type GeneratedImage = {
  src: string;
  width: number;
  height: number;
  /** Widths actually written to disk, ascending. */
  widths: number[];
  blurDataURL: string;
};

export const images: Record<string, GeneratedImage> = {
  "/work/about/IMG_8853.jpg": {
    "src": "/work/about/IMG_8853.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBACdASoQABgAPt1apkyopSOiMAgBEBuJYgCdAdwA3PxsSPq2JmRgAAD+7BE5/a/C6RjlttPzBGthNB7a/ooq8MwmD2AytQmCJE08nm32NmJe9T2zSvEM40/gXJYVfuigANDRFz/zB9LoeHX49hbffKVZWWETuCMdlXNpHxE2/2FKr3BD1CafcU8GGrtRYzwRAFt6zXPxIiNgAAA="
  },
  "/work/events/corporate/John-.jpg": {
    "src": "/work/events/corporate/John-.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADwAwCdASoQABgAPt1cpkyopSOiMAgBEBuJaAABHusPbTX+C3JChWLAAP7+tp/u/3Px+/0Ow6Wmf6E+kWmzYN1A0JAuv2JmoEHovUOJl2fbahDKnCoV+tjdWM2v5aUKl/PvXAuW7R/L5HYEEBzqihHj/2Ou2wyvIpYe8mEjfY97SANzCOQAAA=="
  },
  "/work/events/corporate/John-01014.jpg": {
    "src": "/work/events/corporate/John-01014.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBACdASoQABgAPt1cpkyopSOiMAgBEBuJYgC06YuctWVrE89m1DyqzK+wAAD+/rbdiA1O8jjPKN9sn5/GW8pbfKPzGsZDhef1wsXrMsOX0x+q5KKrSXypfkR+zqkLAc5fa0GD7Rwfe8VGrXlovlCUpmALqXuWtjhVLPaS+5Ff1IAeGs/8+wUKKDwmeTX2lC9l3au3fIzC+Hhbff/7Xkh/BCbOnDhH8pAAAA=="
  },
  "/work/events/corporate/John-06705.jpg": {
    "src": "/work/events/corporate/John-06705.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAAwBSJbACdAD0u8PxpzyAAP7qHW1Gx8FojL+l5wz/BvkIl0sbrZ576Q5QmHRAGXTz4kyKswvynQdVaRr6q1CKWpb15hJP8ibBg5KHlS8gclz3pvgAAAA="
  },
  "/work/events/corporate/John-06777.jpg": {
    "src": "/work/events/corporate/John-06777.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAsAAwBSJbACdAEWvUTJ9uZqwAD+8Uf8RRHrbR1cU2VyKAn+5EmcmPTD9lM/DJeWL4A4oIHSqF+BLNCpNNxD1NvUSAKktaVGyZOrXh8+J6idQAA="
  },
  "/work/events/corporate/John-06808.jpg": {
    "src": "/work/events/corporate/John-06808.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAgCdASoQAAsAAwBSJZACdGaAAvosWTUgQjpAAP703j86H7D+BCbltmw1HRWezYMSjpxwzwghLISBCzrUWjfYu8/XqBYkon+MLm87pHUXYIBXIA72RpEPNDkJ5X2nx0cdKAAA"
  },
  "/work/events/corporate/John-07179.jpg": {
    "src": "/work/events/corporate/John-07179.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwAgCdASoQAAsAAwBSJbACdAYuRNw6MoMOwAD6TfgcSDokd89332//EuJ+7CZL3SFfqoKwixsvDz1aZlIJzZ+xGvEclQmFD03LbqwzXKnEquSjU+zDZrz21Vnvsh4Rdk6mQhR/aPcgUATBmAQzXzxNbe5pG32WBAAAAA=="
  },
  "/work/events/corporate/John-07202.jpg": {
    "src": "/work/events/corporate/John-07202.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAQCdASoQAAsAAwBSJbACdAC8uP1b34AA/tFbhQjxmjW94VJ5ic/SFOJo3h2fV7n/SSp4N+3wjzSk/CGoGgPe6dLbxqR/Im7l4X9q8c3ilUm4hB1sNkiG8aA51xAjFicmqztZlW8QvlX2qEQAAA=="
  },
  "/work/events/corporate/John-07677.jpg": {
    "src": "/work/events/corporate/John-07677.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACQAgCdASoQAAsAAwBSJbACdH8D2PAX8YOuuGoiAAD+haoVmZGLENAXIL6y0hl2+oyMF4KwoYD8zJ158vhz24Aa0lJL/UdmlXNu1dqliz4mofhch1g/pEngmk6hfrlordS15fpfOKH8G4faqfz+d7AAAAA="
  },
  "/work/events/corporate/John-08358.jpg": {
    "src": "/work/events/corporate/John-08358.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQAAsAAwBSJYgCdH8AERSX9gAA/kOLAR3pSoPuMytloW09ti3vEozAA7A35NAphP7W3Idb2+vxR0j/DBx0IoFdY4lAxfjYfiCavHCDcP8kjHJsB2xMYDhzJCQAAA=="
  },
  "/work/events/corporate/John-08367.jpg": {
    "src": "/work/events/corporate/John-08367.jpg",
    "width": 1920,
    "height": 1536,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAA0AAwBSJbACdAYxZMwMGJRQAP6+Ge7i91/FJohB3yuzEsYdurmcbKDHHSLpqq8Sgzra/FxVP3dN20qf84y2eNAEwI1l122r9QerKrfdLy+4979S9sUkj4z/fXwJn8BstqeoAAA="
  },
  "/work/events/corporate/John-08911.jpg": {
    "src": "/work/events/corporate/John-08911.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAAwBSJZQC7AEHImLpCO+EAP7g0XTiRTuA8Yr/jPO4MDA36oIQRPX3CMhv7xZkop6QpFvOIQjwJJ8ntArKbvE2Cwy0PdUjM+c0xQLksw4FBnF+2rpYFgA="
  },
  "/work/events/corporate/John-08982.jpg": {
    "src": "/work/events/corporate/John-08982.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAsAAwBSJaACdAC6iOhHLYAA/eL3QwfUr/HMkH6OeHrAYODXulneZlBVvcW9rfKkTk8iGheD+NHVvLz1BzvNZ3pO2/Vwgc435zduTR4pyRpiAAA="
  },
  "/work/events/corporate/John-09067.jpg": {
    "src": "/work/events/corporate/John-09067.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACwBACdASoQABgAPt1apkyopSOiMAgBEBuJZQCw7dwLhFYw6r+rEfaG7GhuXpoAAPcfIccew4GYXWh9GJZcDwhgXAY0nkBsGbkqvpqZAMSRK3LkoUkzr6PrVooO0FI2PxJ9txE26zwMShkodo27Ub5/OwqNPjMEk1Erdp+hzWlz7rz3HMXiC8BFuufbJc3ceL33ubhqOydtoLBo5IDAgUxsTqAnmAAA"
  },
  "/work/events/corporate/John-09128.jpg": {
    "src": "/work/events/corporate/John-09128.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAsAAwBSJYgCdAYuHWQJfOhHAAD+1OOTu1e3KdrK/8zeP1PHHM3o6chEHhEpcyq2xThJOxdm1h5LhX6DN4c0UyaB8D4paFSxEJ5sfFKqvpQeoAA="
  },
  "/work/events/personal/John-00398.jpg": {
    "src": "/work/events/personal/John-00398.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAADQBACdASoQABgAPt1apkyopSOiMAgBEBuJZACsAyweAAV1v/XaQ1UeW/VhS/orAAD92hmEdG+gQ2FQqGTWpyeboe+fRydFDNTCFe4j/HcCGFnT6uWs/OsuYm83s6HTXj74Mb88fMs0FxXyKCNpLHPLyUd8T/wzxJ6SU8ARqUPNUPfzzML7K3JUMWRju/pkFSkHxCjKT8lrXI5jZ9fGw9IPJvT+qa9s3Pr2g7yeDrewAA=="
  },
  "/work/events/personal/John-00480.jpg": {
    "src": "/work/events/personal/John-00480.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoQAAsAAwBSJbACdH8AENBbmOplMAD9K6G0LoGIbwt+CvETcpa1LkUM2/LhQeETSb8fqvOE1slodE53F1AgPBtr3qo1HSyqztaTwAwJS7DlmRUC1Bcm+ExcM+RKU2fDZMQKzd7AAAA="
  },
  "/work/events/personal/John-00591.jpg": {
    "src": "/work/events/personal/John-00591.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAsAAwBSJQBOkBsiy3h8quVMgAD2vSa9aC4aznQVnNEApaAj4G170M/5uF4pYXjP+g7G4VXvXmSwRugqrGk0azxp0fPdzs3blLxvVHh296r5Iaes0gQq2DFAAA=="
  },
  "/work/events/personal/John-01249.jpg": {
    "src": "/work/events/personal/John-01249.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABQBACdASoQABgAPt1cpkyopSOiMAgBEBuJYgCdAYv+tOoQ4Hv29+TIZzAAAP7nQIVPxbAQt2/aO/Tuaims2uV9Y93EUoFaxcdUmA4E5oBcYMDvWjFNdchQhI/OADCwF3ySXi4DjzW9nRf9rlkGG7Uolyffq+lD6Lcw16fbn3L+Gz65zT6i4sdS7a/vegMPHqX4oUSyKL/CtM9A3FnuZf3hbeODgnAA/5h0ivgA"
  },
  "/work/events/personal/John-07544.jpg": {
    "src": "/work/events/personal/John-07544.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQAAsAAwBSJaACdIExFWzGm0jYoAAA/ubGMrS5bLKc0w5jXuXWfOEH88ZF2UfDLNoWZpPzqANc1SA8G27p6k8+1q9ysL6Wl6zHoQrBC2/Cqs6z4Adn6It556gAAA=="
  },
  "/work/events/personal/John-07559.jpg": {
    "src": "/work/events/personal/John-07559.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAAwBSJZQC7ADs+WEErxWIAP7oAHUNadk0IU5TP18fQjAGGR8SBCiFcU3W0ye/Wa++Mtt0TdGh3g7frFPedvLy/yFCWFbFLgAA"
  },
  "/work/events/personal/John-07698.jpg": {
    "src": "/work/events/personal/John-07698.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAgCdASoQAAsAAwBSJZgCdH8BBABfXoZY6egA/U3TdVfwEjD9jIgstEclFtlHBMBGu8CWyKNNljjfXv2gTFGKNIuv/2cQNLb8dBhAarfUSUuyQexegPqX4AA="
  },
  "/work/events/personal/John-07880.jpg": {
    "src": "/work/events/personal/John-07880.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwAgCdASoQAAsAAwBSJbACsAYvrqoTK6f6HvSAAP63+Zl28qrvhoejcuJg6P/Wezc/fI/bez0+623nr8FtET9oau9yXfx8uRkB2T1Mr+5wFeubvp7Vc9V5dr+VUgGtzX7f2n0weSsBltN/vi/tAAAA"
  },
  "/work/events/personal/John-08171.jpg": {
    "src": "/work/events/personal/John-08171.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQAAsAAwBSJaACdAEPNl9DJpAAAP7UbXPGfjoRXzQSNM76y1dWjUiA1MoSseTj6bDOB8mHllovr3Tty3FxO9g1GxSGZxZBa4wpZrjOGJcVt0zSQOnUaVIElpMjrsCz67AAAA=="
  },
  "/work/main/John-01013.jpg": {
    "src": "/work/main/John-01013.jpg",
    "width": 1920,
    "height": 2400,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADQAwCdASoQABQAPt1apkyopSOiMAgBEBuJZQCAAAZGsNoSrIm3KLAA/oxwXcKOFVj9Hye5RmCG8kFx/v+rzk9S6PUsjbJD/NiFjiYQrB3UDswhr1C2BRy2jzlvRAVeu4jWYosZ46onNHXGbDXfCSeliJYYziLlMpJyax+vmW6gAAAA"
  },
  "/work/proposals/John-03987.jpg": {
    "src": "/work/proposals/John-03987.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAAAQBACdASoQABgAPt1apkyopSOiMAgBEBuJagCdAdwLheOAIG+OKzda7ADieuZw+4fNS6LuEoGopxCdYnqA3vfnAdt8RjG/RZt9yAeQamj+wTgjJT4Ea6KbvAvAYIBm2gxOATQzhJavVF4GUlTqKTqziWHRYAHonA3rMpfW0VnY55XrzNBlb5XSK+6//3mvUQRPaE4R7BXeZGZ49JvhQiqwJ7sTPG1pPhldgrtQu8Pe8Ug73KOqAA=="
  },
  "/work/proposals/John-04015.jpg": {
    "src": "/work/proposals/John-04015.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABwBACdASoQABgAPt1apkyopSOiMAgBEBuJaAC06ywBoPEd9btA2BU0s6SeSADJ3XG36pO/lQILqfy9KAmek7eGQUyR4a/76FQfxEeKFqmzGo4j6U7shr9OoEGnwjPcgqLVlEBdJWp/Ra+UTNLvVY9ydTnvMo3FQpwKiZ5jzZX5O7Ik+OPu5dLF7WhmtXqNvZL6auDlvloWZ4z4GscXLAf+7Q1ezsQA"
  },
  "/work/proposals/John-04310.jpg": {
    "src": "/work/proposals/John-04310.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABwBACdASoQABgAPt1apkyopSOiMAgBEBuJYwCdAdwLf6VnZX1U4Q51EdefoAD8+01QNI9OxTh/HrBS5HAXfWDb8qM32AvbiBMMIwuKTzJ6jteqlj5DrSTos6qFPbtgSUXQohdwNmaIQTBzFtZ6TFmGDt2oO0IhT5PA9/RzTykiTLy35rDooYGXXlV7YzbrUqW5/lXQ+8rDpzTxt566PwTM35BDcCWD2NhfyjwAAAA="
  },
  "/work/proposals/John-04392.jpg": {
    "src": "/work/proposals/John-04392.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABQBACdASoQABgAPt1apkyopSOiMAgBEBuJYwC06YwS3y7CcLIMqSCtXLd4AP7oTUgygRR8bjYj5YHSwhvnY0Y8ESAY0PO+SMb4KUq8p0m23miH3zXFGClh8wadEQoNkltEvXwZWsjDejKfBn94lBRUgAt+jUA1vxEbIROz3TpTFc3KqasiCFKEtLDp4zHVctdjLTTrRWJhSViSaN+y3lwYOOBKP3LVmXogAA=="
  },
  "/work/proposals/John-04413.jpg": {
    "src": "/work/proposals/John-04413.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoQAAsAAwBSJQBYdsXczgqwTcpzfMAA/sGEB/p68rvXZqVmR1OYbQnE9ljeerRNk16ZUjmloiKNUu5iw8sh/2tJfbA/hDMSM+6P6kAOhSXCKikLOnnwLNAAAAA="
  },
  "/work/proposals/John-04518.jpg": {
    "src": "/work/proposals/John-04518.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADQAwCdASoQABgAPt1apkyopSOiMAgBEBuJZACdACBrDyxqbgvxJ4AA4kc3BnNGsHKsXcUNOtiHhMRfIa0DPL3gx7ehDw+zMxunitLiKKBBj2NzygCve8CHRD5DKu7xcuxBYDylATEb3LrmVHXfOhHDU7WJ9+yLvyvUYWfnNviKXPaGqPfxTew2wTXwvGiWmgkt9czWRYSz3+4k4mfImzAA"
  },
  "/work/proposals/John-04979.jpg": {
    "src": "/work/proposals/John-04979.jpg",
    "width": 1920,
    "height": 2560,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoQABUAPt1cpkyopSOiMAgBEBuJYwCdACH5H/JSbwiywxYAAP7nGYvZvrFGM3OsKo5HShtt9chLb8SO3bMJ9hhsNcOhrwYubdCvmsRWH9Fr1+q06juX5Je+tNgvzKiUPi2p9NDqMWIYpC8u5Bh5Rf1BYF2U24YAAAA="
  },
  "/work/proposals/John-05016.jpg": {
    "src": "/work/proposals/John-05016.jpg",
    "width": 1920,
    "height": 2560,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACwAwCdASoQABUAPt1cpkyopSOiMAgBEBuJQAALeq7O9Gg8VnhQAAD+5x8dIQgNHwOQ/TYARo+r75vYHsV6vlEqEzB2UGgjVt9sWwBzVtH9WDmd/Iih1wMsi6r8oSm/MoJIpAk49f9Yj8wH9JXwauG6tZoxK1um3G1atxlBXvChqbjGv4AAAA=="
  },
  "/work/proposals/John-05074.jpg": {
    "src": "/work/proposals/John-05074.jpg",
    "width": 1920,
    "height": 2560,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABwBACdASoQABUAPt1apkyopSOiMAgBEBuJZgCdAYxE394UtSaEZYTD5ppU8AD+ikiRNeej4q9nGmVm0d7d0D2EfiJSxHCmUJKCKfRfjLdGyfOYWd23p/xtcjKrkKKZMPmTWI5xATV8fEdJpGHpm/AtB8svHWpZvkcyUkBP3E8ECEeWBOsFtOhq+20/Bli1BW0hsEIMjQh5AAAA"
  },
  "/work/proposals/John-05080.jpg": {
    "src": "/work/proposals/John-05080.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAsAAwBSJQBOgMW04LnfKcigygAA/vOSM7YNp7o50Ou7twXX6b6hCHaW5wvbpsHQnvWrDfH+N2SmuLam7rUYJK3zVatsCfISSqqC7je5J7V23gAAAA=="
  },
  "/work/proposals/John-05557.jpg": {
    "src": "/work/proposals/John-05557.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoQABgAPt1apkyopSOiMAgBEBuJYwAAW+Iub/Qk+7E9IAD+7E+XCIdSPAqGqNq5G4xj06SIbzF2I9AXb8dWq+sr+OjdoBfSsYC2ZnCmaU1I00ooSTX/QAAA"
  },
  "/work/proposals/John-09220.jpg": {
    "src": "/work/proposals/John-09220.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoQABgAPt1apkyopSOiMAgBEBuJYwC7AdwLgYYyPR4KxG5UPFLDHTgA/gSie8KMhdwANvpDnaEYvCeipAsVBm6PenIuMvUBfSP1/UzMTVgPuKAxVz35bzBvNwerhYnJ+bWYJhFTyA2wnUtw3apfSL7Qm4O7zHcB2Im6B+wF8XfEAyqkTco9yzCoxxVlp9EeeahXHjNsnAIOLMLZOBkAAA=="
  },
  "/work/proposals/John-09228.jpg": {
    "src": "/work/proposals/John-09228.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAADQBACdASoQABgAPt1apkyopSOiMAgBEBuJQBdmUGZj2ATm4wSIjD+rMcnXVS0RgAD+tA0k/0gT+OLEWscmJ2KoQt9BDEwcaWuqjqM8QJZ2iBlVCwCqR16l55GXyLhvgyeUw2N+1A7Y2zBwE4Bn1QV/EZv4y1YZVd7O/YB21oD6TeFj3po/Tqeycukb38l6t3sgCdiWnMn5/6Xr4wxXqjwHq4nOjR6YyPv3rl/eaRQgogDf5NPMY1NjihjiJAAA"
  },
  "/work/proposals/John-09426_edited.jpg": {
    "src": "/work/proposals/John-09426_edited.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAsAAwBSJQBOgCHvYA2pl9AA/pmAzkC2OAB6tODaYQ4cHShF/oXQmQac+u+YVqWM8uAfIECy6vLv4v93JQKeJ1UpIpccbGwRIUVuypwAAA=="
  },
  "/work/proposals/John-09442.jpg": {
    "src": "/work/proposals/John-09442.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAsAAwBSJQBOgP4AzM+Y11DQAP60LwiVUeIxDoA9J50K1rIJa1AEJWqxByVUF1xChkZhGNHSR4PjbBz/mb74Abg1OjgzPYk2/YLqR92XhbProD8QsnAUhh5IAAAA"
  },
  "/work/proposals/John-09463.jpg": {
    "src": "/work/proposals/John-09463.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQAAsAAwBSJQBOgMWg3nmXL1DIKADLT9s2JbBkxjNbGhRnhycGTJ+/Mz0Pr8Og06ucJEmNVZKvwlva7IVKLgEvlpCuTUyOGxnD2rsLfxFe53+ey9yxs1VoPl5Yafty/cyV6XuuXgAAAA=="
  },
  "/work/videography/John-07525.jpg": {
    "src": "/work/videography/John-07525.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAsAAwBSJZgCdAB15zYAAP5g/u11TpD+WBrL81Y/7JtmYAlp7tUeqbvpkmOn29zpgpvP5Qr2mOyaKK8t/gA41YAAAA=="
  },
  "/work/weddings/John-00317.jpg": {
    "src": "/work/weddings/John-00317.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwAwCdASoQABgAPt1apkyopSOiMAgBEBuJagCdABjWCeOgSCC0AADNcGLLSW8y3BHKslXo48J3mWj1q7xWDInL8AJfTyiUUlJB5OBkEzI8Aq4O+p01CvBlpDde/x+DCLE01R8GcDeh1pzAk4d3ppg+KL0cRdRM1WsiJDS1/+onft1e/XJay6MRnb/Q7lBWAAA="
  },
  "/work/weddings/John-00456.jpg": {
    "src": "/work/weddings/John-00456.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwAgCdASoQAAsAAwBSJZgCdAYv/zUQhP0cYAD9nLWX/Kb4kZvm8APydOu/Q8O/M1GN4BDjSb9RXeywVFIAdSMrX3F5xxF0FljSMfku0xQVfJMSUyunIia9xosY1Q0ysU1a4Ju363TyhKazlfv6KVo0+GHPdbwvxKgJCQ8AAAA="
  },
  "/work/weddings/John-00460.jpg": {
    "src": "/work/weddings/John-00460.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAACwBACdASoQABgAPt1cpkyopSOiMAgBEBuJZgCdMoAlsxexStVK+P08Cv4C3wwAAMp1D8iygoIX4VSJxrozCALaT63gjFHjjq207OJe9GX4zbp1TuPLrqEZHcyrjWSOAcn5oqvrdGqVPSVd8jWuLZc2MPWXLg8E5ud/SD7E6m4La9zkEgRNDHWMwt88DsJXcbmbuIbqANTQyjTjaSA9kPP8Lf/6dQ2FAayKezsB951TPY+/T8FFJpOIAAA="
  },
  "/work/weddings/John-00484.jpg": {
    "src": "/work/weddings/John-00484.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoQAAsAAwBSJYgCdAEfNhrlsDvAAAD+4V1GtM4v9Q2HWZB1i3aIFLE5B6fnd69KCzoR9ehWr+e74b289OkRj5XLiIItvNnrztrr1Fr7ZZc8OrFFeDGJpJ4Fa4Rsy4UsAAA="
  },
  "/work/weddings/John-01344.jpg": {
    "src": "/work/weddings/John-01344.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAsAAwBSJZQCdAEPSQn75lzQAAD+9DTsFXN2RIZvdniaSyLKNUfb8p7ya8qtxDdSoQ9h417dd/HEsiQGWo0Mk4Nq/JCUvjkfzY7gAAA="
  },
  "/work/weddings/John-01586.jpg": {
    "src": "/work/weddings/John-01586.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQAAsAAwBSJYgCdAEPA/MC+oAA/uU6He8O32tEFPhbIWLaZzZ4lTblr1EZBmpYvm7a3q/yIbPzTwaWE4uIkcYLH1wq9sMG85/Ui0RSgKE+JkF9DcU9OKktYaeQAA=="
  },
  "/work/weddings/John-01599.jpg": {
    "src": "/work/weddings/John-01599.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoQAAsAAwBSJQBOgMYY399CTpnXJ/gA/vNSSncCGl7D3rO7gwY5v5kMyjdJ8i1qha4lSTx7tfeodhffj6zfB+UVlX01S9eQpJ/zhxFlXOez5PB5NERCMNLzJN0XM0AA"
  },
  "/work/weddings/John-01681.jpg": {
    "src": "/work/weddings/John-01681.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAQCdASoQAAsAAwBSJYgCdACPNKAA/vAaffZwbHLBNrsHE1n4o/IOXouapcy83lP7c4ilfh40OxRH6xpPo58CQOEvbZI6bmU7/LYpc7BFtdG3sWZAPAAA"
  },
  "/work/weddings/John-01740.jpg": {
    "src": "/work/weddings/John-01740.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoQABgAPt1apkyopSOiMAgBEBuJYwAD5UIPDcsL6UapsxjphAAA/uqltLLcGXgzJga6f34t1wsKZ0CO5vYFsENiv2WpB81NN+PrEH+Cq7d++Xe+j2rYJb0ZZjgGJoKU0XOlGJ/bre/mtR18/JNYMZbggTvWdVn3vhKPEFGA47EdfpOwliAAAA=="
  },
  "/work/weddings/John-01773.jpg": {
    "src": "/work/weddings/John-01773.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQAAsAAwBSJZQCdAEOQ7a+L0AA/rI6Gl85U56zGgECMe8WJqcRInykd2piAK9gRo9ML8DwSeR+hMf3vLx0WGN+EDfcBGGjuMtBNWL/dqMmSWAk8kCfGlmJozQAAA=="
  },
  "/work/weddings/John-03019.jpg": {
    "src": "/work/weddings/John-03019.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQAwCdASoQABgAPt1apkyopSOiMAgBEBuJYgAAJVkX7j2zgAD9IiDvfkDTxAcYW15hKClo4dUgYbOWtfzNqx28JON8P07rovu7cEhRJcdcL/ZfBAESVpeyh4+bjZP/aY0sqeI5uN3wy/9/JJmtB8mpUrmdJ1NblPL/lDcZ2+j0MPKNMnuf3schvgkk8/j9lqCWRmmjsISnvJSf0CEwAAAA"
  },
  "/work/weddings/John-03291.jpg": {
    "src": "/work/weddings/John-03291.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQBACdASoQABgAPt1apkyopSOiMAgBEBuJZgC7AdwLhFcieWZIwew3Se2UoJ6v0AD+6nsjHApdupabZLLxR00i+By+gLwvXlf9r5jabxYZorrXzlIstPhGCmbyBYJEETfacH4SZrwOOb/wbzy5+Z9wTvhgJBoUMRdP0ppFDMxz8zKpZavQ181q7LE+Q1ZIrLRALug6d2ZsgdjipoMTLZz/B31IgAAA"
  },
  "/work/weddings/John-04315.jpg": {
    "src": "/work/weddings/John-04315.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAsAAwBSJQBOgBZzc1bwzAD9mqvVUzMOlopT8+ZwhnAaa3GAE/rAa1C/WmymRcyJrASDmXFL73nYaVT3PNHiuoJKDDFKHXX2Xs2KqI10Uc/J/iBxOc4GLQAAAA=="
  },
  "/work/weddings/John-04559.jpg": {
    "src": "/work/weddings/John-04559.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoQABgAPt1cpkyopSOiMAgBEBuJYwC7IKnCLZJlcb28xbxoAAD+0+blrujWBEk6VxUm1XX8V6MHiSJlbcufJAQGdHtRLZEGXPJj+PEhpLzQJSULgdpy6m9I+XIW9gk3PtZuey7NMStTrLh2ugMDnxnxrNqZCkrSuUakqWMZvBp2/fztid7Ycg3j1DQAAA=="
  },
  "/work/weddings/John-04605.jpg": {
    "src": "/work/weddings/John-04605.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoQABgAPt1cpkyopSOiMAgBEBuJYwBUQoYfAJPyMbv+RgndgAD+1PvkNpTQIcxFrifkQhyVBYogdT5A2obwL6AMY7jKK2D4Tnv2taDmiaOJ7aYpcmSp84i5OjZ8l5Ercmv86AdtL6p6BGhc2roQENck4FemRckbDSteHRqYU8C/JAJhaMIn+Sq/V0igAA=="
  },
  "/work/weddings/John-04669.jpg": {
    "src": "/work/weddings/John-04669.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADQAwCdASoQABgAPt1cp0yopSOiMAgBEBuJQBdgA81rZt0InbX1XEAA4DcQ17piHiQqDBA4dDqni7YZcTRKNIi1RU8fJJUrpn9RWEXyWltOBsXAEbU7hvEWR1liKNzr9Lv2jEIiDVKJ73NdeIwwgPkXa92RDb02MOTrHYhvsxsbkcrQG9ghZBb6gUl6fxEwEAAAAA=="
  },
  "/work/weddings/John-08678.jpg": {
    "src": "/work/weddings/John-08678.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoQAAsAAwBSJQBOgMWM2aVO1gAA+yPT24VD1NVBP9d5zWL+nnBJKO80z++9sLEVFybAbVKbKUZrsFPK9pUENsIKWpit8nlkQ+UYnBSh9gEcS6gznV5erFZbADp8AAAA"
  },
  "/work/weddings/John-08695.jpg": {
    "src": "/work/weddings/John-08695.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABQBACdASoQABgAPt1cp0yopSOiMAgBEBuJZQCAAGT4N0TVTuyDfGQ2RGWgAP7oIhrZBruprLJdjD7oEZ5jgkh68i+hdu+Yexf/XfPqHwsltFaSF2RVyfeciOzho/JdiPd3XsTT2aDZ6QuAE0k1iiSTCo2RnDDAxm/RnaWY5GJgEVxoTrPMlf7w0zHBOtmH2hYkAA=="
  },
  "/work/weddings/John-08966.jpg": {
    "src": "/work/weddings/John-08966.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAABwBACdASoQABgAPt1apkyopSOiMAgBEBuJQBdgMYxaqL93/vSKvJq3EztXAAD8MN6ixzfU4veF+1iCxIe9fUz5dWEliYWInE5EeCRRgKSmCSYaiQgGCvBYsA2TCntPfcoKRnFLeludExPiMNgamUOToTMZ78cDhucJ9KNkYRybh5FmBIHim0zYh2cjS/BYzpzTzb+fP3KbQdWSfGrGrzTa+9N1zJyvYvRAuke91cyN+UsLkfAAAA=="
  },
  "/work/weddings/John-09199.jpg": {
    "src": "/work/weddings/John-09199.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADwAwCdASoQABgAPt1apkyopSOiMAgBEBuJaACsAf9IOSm5m3jtfadAAPjj89tmtkulqu+OYix+DXNuqz148g5UodXtaxx9L18Fj8UezpPwWwkc3ddEa2XYU95JlwROtyOYLSeVKpZ84lwCDEauG+GP5OAiZhPHNuhBzB6bT/GXRXFgkUDJXVDRYTjyuDNWC8awgf4lGNOfp38oi5lMLnM8nWAAAA=="
  },
  "/work/weddings/John-09234.jpg": {
    "src": "/work/weddings/John-09234.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAQBACdASoQABgAPt1apkyopSOiMAgBEBuJYgC7AYwSd5pjVdWXk28WggD+GbdiBJVg6aqajZWn8uW3iihLwglfr44mtDngSzz9tIQwCjsX0YXViAD6FyD5o0n18eBk/0hwiq8PjX8khdE+NzF8+xtViFcP39kJ4mnYUfwpfMvgYsF0Vb7XjTCDEedHmuT8GteHW8BbtPE9Fj1bGTLUjaAA"
  },
  "/work/weddings/John-09345.jpg": {
    "src": "/work/weddings/John-09345.jpg",
    "width": 1920,
    "height": 2880,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAADwBACdASoQABgAPt1cpkyopSOiMAgBEBuJYgAL4A//DD8OY1MQdKW0fPOX6OokewAA/ukuPKp9vS515Za92HfEwdFKluJgHOvFOTHoc4gZ891PY2rP2ci3KYZLCWOaz+5yinRTH7f1RenXVpHKaARBWfKAQ2WsjeYrWCtxjiE9h3rGLOAHxpWt9bZuFOGQq8CwzPMuaLhlvGzFY7uQC/z98oXQPhwAAAA="
  },
  "/work/weddings/John-09685.jpg": {
    "src": "/work/weddings/John-09685.jpg",
    "width": 1920,
    "height": 1280,
    "widths": [
      480,
      960,
      1440,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAsAAwBSJZACdADyoAikxUAA/o8rNy7AxhRooP0I2QmaNeoOYY4P1ED7/iJ4aoJsxF5ZQpUdlfGMi2NnLMAsX+TCPztWay8zfHFqxe3hWxCgj8aBomAA"
  }
};
