/**
 * assets/<collection>/**  →  public/work/<collection>/**
 *
 * Masters stay in assets/ (git-ignored, never deployed). This writes the
 * web-sized derivatives the site actually serves, plus a generated manifest
 * carrying each image's dimensions and a blur placeholder.
 *
 *   node scripts/optimize-images.mjs
 *
 * Emits one WebP per width in WIDTHS. GitHub Pages serves static files with
 * no image optimizer, so the responsive variants have to exist on disk —
 * lib/image-loader.ts points next/image at them, which keeps real srcsets
 * rather than shipping one large file to every device.
 *
 * public/work is fully derived, so it's wiped and rebuilt each run.
 */
import sharp from "sharp";
import { readdir, mkdir, writeFile, stat, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const SRC = "assets";
const OUT = path.join("public", "work");

/* The widest slot renders at 890px CSS, so 1920 covers it at 2x. These must
   match `deviceSizes` in next.config.mjs — the loader is only ever asked for
   widths Next knows about. */
const WIDTHS = [480, 960, 1440, 1920];
const QUALITY = 80;

const isImage = (f) => /\.(jpe?g|png|webp|tiff?)$/i.test(f);

async function collectDirs(dir, base = "") {
  const entries = await readdir(dir, { withFileTypes: true });
  const here = entries.some((e) => e.isFile() && isImage(e.name)) ? [base] : [];
  const nested = await Promise.all(
    entries
      .filter((e) => e.isDirectory())
      .map((e) => collectDirs(path.join(dir, e.name), path.join(base, e.name))),
  );
  return [...here, ...nested.flat()];
}

if (existsSync(OUT)) await rm(OUT, { recursive: true });

const categories = (await collectDirs(SRC)).filter(Boolean);
const manifest = {};
let bytesIn = 0;
let bytesOut = 0;

for (const category of categories) {
  const inDir = path.join(SRC, category);
  const outDir = path.join(OUT, category);
  await mkdir(outDir, { recursive: true });

  for (const file of (await readdir(inDir)).filter(isImage).sort()) {
    const from = path.join(inDir, file);
    const name = path.parse(file).name;
    /* The manifest key stays a .jpg path so content.ts reads naturally; the
       loader swaps in the width and the .webp extension at request time. */
    const key = `/work/${category}/${name}.jpg`;

    const meta = await sharp(from).rotate().metadata();
    const widths = WIDTHS.filter((w) => w <= meta.width);
    if (widths.length === 0) widths.push(meta.width);

    for (const w of widths) {
      const to = path.join(outDir, `${name}-${w}.webp`);
      // Metadata is stripped by default — that drops GPS, which for wedding
      // work means venue and home addresses.
      await sharp(from)
        .rotate()
        .resize({ width: w, withoutEnlargement: true })
        .toColourspace("srgb")
        .webp({ quality: QUALITY })
        .toFile(to);
      bytesOut += (await stat(to)).size;
    }

    const largest = await sharp(
      path.join(outDir, `${name}-${widths[widths.length - 1]}.webp`),
    ).metadata();

    const blur = await sharp(from).rotate().resize(16).webp({ quality: 45 }).toBuffer();

    manifest[key] = {
      src: key,
      width: largest.width,
      height: largest.height,
      widths,
      blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    };

    bytesIn += (await stat(from)).size;
    console.log(`${category}/${file}  →  ${widths.join(", ")}`);
  }
}

const banner = `/* GENERATED by scripts/optimize-images.mjs — do not edit by hand. */\n`;
const type = `export type GeneratedImage = {
  src: string;
  width: number;
  height: number;
  /** Widths actually written to disk, ascending. */
  widths: number[];
  blurDataURL: string;
};\n\n`;
await writeFile(
  path.join("lib", "generated-images.ts"),
  `${banner}\n${type}export const images: Record<string, GeneratedImage> = ${JSON.stringify(
    manifest,
    null,
    2,
  )};\n`,
);

console.log(
  `\n${Object.keys(manifest).length} images × ${WIDTHS.length} widths  ${(
    bytesIn / 1e6
  ).toFixed(0)}MB → ${(bytesOut / 1e6).toFixed(1)}MB`,
);
