/**
 * assets/<category>/*.jpg  →  public/work/<category>/*.jpg
 *
 * Masters stay in assets/ (git-ignored, never deployed). This writes the
 * web-sized derivatives Next actually serves from, plus a generated manifest
 * carrying each image's dimensions and a blur placeholder.
 *
 *   node scripts/optimize-images.mjs
 *
 * Re-run it whenever you drop new photos into assets/. It's idempotent.
 */
import sharp from "sharp";
import { readdir, mkdir, writeFile, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const SRC = "assets";
const OUT = path.join("public", "work");

/* The widest slot renders at 890px CSS; 2560 covers that at 3x DPR with
   room to spare. Anything beyond is pixels no device will ever ask for. */
const MAX_EDGE = 2560;
const QUALITY = 88;

const isImage = (f) => /\.(jpe?g|png|webp|tiff?)$/i.test(f);

/* Walks nested folders, so assets/events/corporate maps to
   public/work/events/corporate. Collections that need subsections just
   nest a directory. */
async function collectDirs(dir, base = "") {
  const entries = await readdir(dir, { withFileTypes: true });
  const here = entries.some((e) => e.isFile() && isImage(e.name)) ? [base] : [];
  const nested = await Promise.all(
    entries
      .filter((e) => e.isDirectory())
      .map((e) => collectDirs(path.join(dir, e.name), path.join(base, e.name))),
  );
  return [...here, ...nested.flat()];
}

const categories = (await collectDirs(SRC)).filter(Boolean);

const manifest = {};
let bytesIn = 0;
let bytesOut = 0;

for (const category of categories) {
  const inDir = path.join(SRC, category);
  const outDir = path.join(OUT, category);
  if (!existsSync(outDir)) await mkdir(outDir, { recursive: true });

  const files = (await readdir(inDir)).filter(isImage).sort();

  for (const file of files) {
    const from = path.join(inDir, file);
    const name = `${path.parse(file).name}.jpg`;
    const to = path.join(outDir, name);
    const src = `/work/${category}/${name}`;

    const pipeline = sharp(from)
      .rotate() // bake in EXIF orientation before we strip metadata
      .resize({
        width: MAX_EDGE,
        height: MAX_EDGE,
        fit: "inside",
        withoutEnlargement: true,
      })
      .toColourspace("srgb");

    // Metadata is stripped by default — that drops GPS coordinates, which
    // for wedding work means venue and home addresses.
    const { width, height } = await pipeline
      .jpeg({ quality: QUALITY, mozjpeg: true })
      .toFile(to);

    // 16px-wide WebP, inlined as a data URI for the blur-up placeholder
    const blur = await sharp(from)
      .rotate()
      .resize(16)
      .webp({ quality: 45 })
      .toBuffer();

    manifest[src] = {
      src,
      width,
      height,
      blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    };

    bytesIn += (await stat(from)).size;
    bytesOut += (await stat(to)).size;
    console.log(
      `${category}/${file}  →  ${width}x${height}  ${(
        (await stat(to)).size / 1e6
      ).toFixed(2)}MB`,
    );
  }
}

const banner = `/* GENERATED by scripts/optimize-images.mjs — do not edit by hand. */\n`;
const type = `export type GeneratedImage = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};\n\n`;
await writeFile(
  path.join("lib", "generated-images.ts"),
  `${banner}\n${type}export const images: Record<string, GeneratedImage> = ${JSON.stringify(
    manifest,
    null,
    2,
  )};\n`,
);

console.log(
  `\n${Object.keys(manifest).length} images  ${(bytesIn / 1e6).toFixed(
    0,
  )}MB → ${(bytesOut / 1e6).toFixed(1)}MB  (${(
    100 -
    (bytesOut / bytesIn) * 100
  ).toFixed(1)}% smaller)`,
);
